adding messagefeedservlet hardcode
KevinAlamo/team-15-codeu pull request #11
Opened 2019-05-28 19:50 UTC by conniewu1

2019-05-28 20:44 UTC, conniewu1 commented
changed code in messagefeedservlet class

2019-05-28 22:13 UTC, matthew-chinn requested changes

2019-05-28 22:13 UTC, matthew-chinn commented on src/main/webapp/js/feed-loader.js
> +}).then((messages) => {
Promises can make code hard to read if we don't keep it styled nicely :( At our next meeting, we can look into adding an automated formatter to style our guide for us, but for now, can we format it so it looks something like this:
```
fetch(url)
    .then((response) => {
           <code goes here>
    }).then((messages) => {
          <code goes here>
    });
```

2019-05-29 04:01 UTC, conniewu1 commented on src/main/webapp/js/feed-loader.js
> +}).then((messages) => {
got it, thanks!!

2019-05-29 04:15 UTC, matthew-chinn approved these changes
Thanks Connie!!

2019-05-29 14:20 UTC, merged