Stats page kevin
KevinAlamo/team-15-codeu pull request #12
Opened 2019-05-29 04:48 UTC by KevinAlamo

I created the Stats Page servlet and added Datastore logic which will count the number of messages on the site. Some of the commits fixed mistakes I made in where I put the code.

2019-05-29 05:07 UTC, KevinAlamo commented
This branch was done first

2019-05-29 22:11 UTC, matthew-chinn requested changes

2019-05-29 22:11 UTC, matthew-chinn commented on src/main/java/com/google/codeu/data/Datastore.java
> +	 }
we'll work on getting a formatter at the next meeting, but for now can we use 2 spaces of indentation like the rest of the Java code?

2019-05-31 19:35 UTC, KevinAlamo commented on src/main/java/com/google/codeu/data/Datastore.java
> +	 }
I added the spaces

2019-05-31 23:30 UTC, matthew-chinn approved these changes

2019-05-31 23:30 UTC, matthew-chinn commented
Ooh looks like you have conflicts! Exciting :)

2019-06-02 04:02 UTC, merged