Stats page html
KevinAlamo/team-15-codeu pull request #13
Opened 2019-05-29 04:51 UTC by KevinAlamo

Here I made two files. The stats html page which displays the total number of messages. As well as the JavaScript which gets the number from the Stats page Servlet.

2019-05-29 04:53 UTC, KevinAlamo commented
I noticed that this branch also includes the same things as the other branch I made, plus the new stuff.

2019-05-29 05:07 UTC, KevinAlamo commented
This is the second branch

2019-05-29 22:13 UTC, matthew-chinn requested changes

2019-05-29 22:13 UTC, matthew-chinn commented on src/main/webapp/js/stats-page-loader.js
> +     return statElement;
It looks like this is only 1 space of indentation, can we make it 2 please?

2019-05-29 22:13 UTC, matthew-chinn commented on src/main/webapp/js/stats-page-loader.js
> +     fetchStats();
Same here!

2019-05-29 22:13 UTC, matthew-chinn commented on src/main/webapp/stats.html
> +  <hr/>
is this supposed to be br instead of hr?

2019-06-02 04:14 UTC, KevinAlamo commented on src/main/webapp/stats.html
> +  <hr/>
I looked it up and the codeu site says hr/. The br/ makes extra space underneath the header which looks different from the example given.

2019-06-03 21:40 UTC, matthew-chinn commented on src/main/webapp/stats.html
> +  <hr/>
Oh interesting! I didn't know there was an hr tag, lesson learned :)

2019-06-03 21:41 UTC, matthew-chinn approved these changes

2019-06-03 21:41 UTC, matthew-chinn commented on src/main/java/com/google/codeu/data/Datastore.java
> +  public int getTotalMessageCount(){
Whoops sorry I must have missed this one before. Can you fix this indentation too? I'll give you the approval now, so hopefully you can submit as soon as you update this, but it may make you have to go through review again...

2019-06-04 00:46 UTC, KevinAlamo commented on src/main/java/com/google/codeu/data/Datastore.java
> +  public int getTotalMessageCount(){
Is this what you meant with indentation?

2019-06-04 15:58 UTC, matthew-chinn commented on src/main/java/com/google/codeu/data/Datastore.java
> +  public int getTotalMessageCount(){
Yes!! The only thing now is that closing } after the return statement should line up with the beginning of the line (2 spaces in)

2019-06-04 16:04 UTC, matthew-chinn commented
It looks like you also have some merge conflicts, so try fixing those up!

2019-06-04 23:20 UTC, merged