added a function to get set of users who have sent a message
KevinAlamo/team-15-codeu pull request #15
Opened 2019-05-29 21:51 UTC by sirisjo

2019-05-29 21:52 UTC, sirisjo commented
not sure why it thinks I deleted everything, I just added my 1 method to the bottom.

2019-05-29 22:24 UTC, matthew-chinn requested changes

2019-05-29 22:24 UTC, matthew-chinn commented on src/main/java/com/google/codeu/data/Datastore.java
> +                    .addSort("timestamp", SortDirection.DESCENDING);
Can we make this indentation either 4 spaces or 2? I think Google's Java style guide says 4 spaces if we are continuing the same line, but 2 spaces if it is a new code block (such as after {}). However, we will try using a formatter later to do this for us, but for now lets make it somewhat consistent with the rest!

2019-05-29 22:24 UTC, matthew-chinn commented on src/main/java/com/google/codeu/data/Datastore.java
> +            .addSort("timestamp", SortDirection.DESCENDING);
Same here :)

2019-05-29 22:24 UTC, matthew-chinn commented on src/main/java/com/google/codeu/data/Datastore.java
> +	  Set<String> users = new HashSet<>();
Please line up this indentation!

2019-05-30 21:23 UTC, sirisjo commented
I think I committed the same thing twice, oops...

2019-05-31 00:52 UTC, matthew-chinn approved these changes
Thanks! lgtm

2019-05-31 03:24 UTC, merged